package com.example.fella.tdm1_project;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Bundle;
import android.os.Environment;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.MotionEvent;
import android.view.View;
import android.widget.ImageView;
import android.widget.RelativeLayout;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

/**
 * Created by RIMA on 16/04/2017.
 */

public class DegatsApparents extends AppCompatActivity {
    Bitmap myBitmap;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getSupportActionBar().show();
        setTitle("Dégats apparents");
        setContentView(R.layout.degats);

        final ImageView imageView = (ImageView) findViewById(R.id.img);
        final RelativeLayout rr = (RelativeLayout) findViewById(R.id.imager);
        imageView.setOnTouchListener(new View.OnTouchListener() {

            @Override
            public boolean onTouch(View v, MotionEvent event) {

                if (event.getAction() == MotionEvent.ACTION_DOWN) {
                    int x = (int) event.getX();
                    int y = (int) event.getY();


                    RelativeLayout.LayoutParams lp = new RelativeLayout.LayoutParams(
                            RelativeLayout.LayoutParams.WRAP_CONTENT,
                            RelativeLayout.LayoutParams.WRAP_CONTENT);
                    ImageView iv = new ImageView(getApplicationContext());
                    lp.setMargins(x, y, 0, 0);
                    iv.setLayoutParams(lp);
                    iv.setImageDrawable(getResources().getDrawable(
                            R.drawable.croix));
                    rr.addView(iv);
                }
                return false;
            }
        });



    }

    public String saveBitmap(Bitmap bitmap) {
        String filePath = Environment.getExternalStorageDirectory()
                + File.separator + "Pictures/screenshot.png";
        File imagePath = new File(filePath);
        FileOutputStream fos;
        try {
            fos = new FileOutputStream(imagePath);
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, fos);
            fos.flush();
            fos.close();
            //sendMail(filePath);
        } catch (FileNotFoundException e) {
            Log.e("GREC", e.getMessage(), e);
        } catch (IOException e) {
            Log.e("GREC", e.getMessage(), e);
        }
        return filePath;
    }

    public void sendMail(String path) {
        Intent emailIntent = new Intent(android.content.Intent.ACTION_SEND);
        emailIntent.putExtra(android.content.Intent.EXTRA_EMAIL,
                new String[] { "receiver@website.com" });
        emailIntent.putExtra(android.content.Intent.EXTRA_SUBJECT,
                "Truiton Test Mail");
        emailIntent.putExtra(android.content.Intent.EXTRA_TEXT,
                "This is an autogenerated mail from Truiton's InAppMail app");
        emailIntent.setType("image/png");
        Uri myUri = Uri.parse("file://" + path);
        emailIntent.putExtra(Intent.EXTRA_STREAM, myUri);
        startActivity(Intent.createChooser(emailIntent, "Send mail..."));
    }

    public String envoyerMail(View v){
        View v1 = findViewById(R.id.imager);
        // View v1 = iv.getRootView(); //even this works
        // View v1 = findViewById(android.R.id.content); //this works too
        // but gives only content
        v1.setDrawingCacheEnabled(true);
        myBitmap = v1.getDrawingCache();
        return saveBitmap(myBitmap);

    }

    public void chargerActivity(View view){
        Intent i = getIntent();
        Vehicule vi = (Vehicule) i.getParcelableExtra("VehiculeAccidenté");
        int typeAccident= getIntent().getExtras().getInt("typeAccident");
        InfoDetaille diV = (InfoDetaille) i.getSerializableExtra("detailAccident");
        personne pers = (personne) i.getSerializableExtra("PersonneTiers");



        Intent intent=null;
        switch (view.getId()) {

            case R.id.butSuiv6:

                intent = new Intent(this, Circonstance_Activity.class);
                intent.putExtra("PersonneTiers", pers);
                intent.putExtra("VehiculeAccidenté", vi);
                intent.putExtra("detailAccident", diV);
                intent.putExtra("typeAccident",typeAccident );
                intent.putExtra("photo",typeAccident );


                break;
        }
        startActivity(intent);
    }
}
